"""
pipeline.portfolio_truth.update
--------------------------------
CLI to update the truth file from live sources.

Usage:
  python -m pipeline.portfolio_truth.update           # run, show diff, prompt
  python -m pipeline.portfolio_truth.update --force  # apply without prompting
  python -m pipeline.portfolio_truth.update --dry-run # show what would change, don't write
  python -m pipeline.portfolio_truth.update --init    # bootstrap from scratch (no existing file)
  python -m pipeline.portfolio_truth.update --emit-watchlist # also rewrite my_tickers.txt
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from pipeline.portfolio_truth import (
    TRUTH_FILE, WATCHLIST_FILE, _now_iso, diff_states, fetch_live_state,
    load_truth, merge_from_live, print_status, save_truth, status,
)


def _confirm(prompt: str, default_yes: bool = True) -> bool:
    suffix = "[Y/n]" if default_yes else "[y/N]"
    ans = input(f"{prompt} {suffix} ").strip().lower()
    if not ans:
        return default_yes
    return ans in ("y", "yes")


def _emit_watchlist_file(watchlist: list[str]) -> None:
    """Rewrite my_tickers.txt from the truth file's watchlist."""
    lines = [f"# AUTO-GENERATED by pipeline.portfolio_truth.update at {_now_iso()}\n"]
    lines.append("# Source: data/portfolio_truth.json -> watchlist field\n")
    lines.append("# Edit the truth file (not this) to change the watchlist.\n")
    lines.append("\n")
    for t in watchlist:
        lines.append(f"{t}\n")
    WATCHLIST_FILE.write_text("".join(lines))
    print(f"✓ Wrote {len(watchlist)} watchlist tickers to {WATCHLIST_FILE}")


def main() -> int:
    p = argparse.ArgumentParser(
        description="Update data/portfolio_truth.json from broker + config files"
    )
    p.add_argument("--force", action="store_true",
                   help="Apply changes without prompting")
    p.add_argument("--dry-run", action="store_true",
                   help="Show what would change, don't write anything")
    p.add_argument("--init", action="store_true",
                   help="Bootstrap from scratch (ignore existing truth file)")
    p.add_argument("--emit-watchlist", action="store_true",
                   help="Also rewrite my_tickers.txt from the truth file's watchlist")
    args = p.parse_args()

    # Gather current state
    if args.init or not TRUTH_FILE.exists():
        current = {
            "schema_version": 1, "asof": None, "source": "default",
            "equity": {}, "mutual_funds": {}, "sgbs": {}, "watchlist": [],
        }
        print("No existing truth file; bootstrapping from scratch.")
    else:
        current = load_truth()

    # Pull live state
    print("Pulling live state from broker, mfs.json, sgbs.json, my_tickers.txt ...")
    live = fetch_live_state()
    print(f"  equity={len(live['equity'])}  mf={len(live['mutual_funds'])}  "
          f"sgb={len(live['sgbs'])}  watchlist={len(live['watchlist'])}")

    # Diff
    diff = diff_states(current, live)
    if diff["is_clean"]:
        print("✓ Truth file is up to date. No drift. Nothing to do.")
        return 0

    print()
    print("Drift detected:")
    for sect in ("equity", "mutual_funds", "sgbs", "watchlist"):
        d = diff[sect]
        changes = {k: v for k, v in d.items() if v}
        if not changes:
            continue
        print(f"  {sect.upper()}:")
        for kind, items in changes.items():
            print(f"    {kind}: {items}")
    print()

    if args.dry_run:
        print("Dry-run mode; no files written.")
        return 0

    # Build the new truth
    new_truth = merge_from_live(live, current)

    if not args.force:
        if not _confirm(f"Apply these changes to {TRUTH_FILE}?", default_yes=True):
            print("Aborted. No files written.")
            return 1

    save_truth(new_truth, source="auto-update")
    print(f"✓ Wrote {TRUTH_FILE}")
    print(f"  asof={new_truth['asof']}")
    print(f"  equity={len(new_truth['equity'])}  mf={len(new_truth['mutual_funds'])}  "
          f"sgb={len(new_truth['sgbs'])}  watchlist={len(new_truth['watchlist'])}")

    if args.emit_watchlist:
        _emit_watchlist_file(new_truth["watchlist"])

    return 0


if __name__ == "__main__":
    sys.exit(main())
